<?php

namespace block_cdo_survey\helpers;

use core_external\external_single_structure;
use core_external\external_value;

class external_helper
{
    public static function form_data_external(): external_single_structure {
        return new external_single_structure(
            [
                'middleName' => new external_value(PARAM_TEXT, 'Telephone number', VALUE_OPTIONAL),
                'isNewPassport' => new external_value(PARAM_BOOL, 'Telephone number', VALUE_DEFAULT, false),
                'telephone' => new external_value(PARAM_TEXT, 'Telephone number', VALUE_OPTIONAL),
                'citizenship' => new external_value(PARAM_TEXT, 'Citizenship', VALUE_OPTIONAL),
                'snils' => new external_value(PARAM_TEXT, 'SNILS', VALUE_OPTIONAL),
                'inn' => new external_value(PARAM_TEXT, 'INN', VALUE_OPTIONAL),
                'innFile' => new external_value(PARAM_RAW, 'INN File (base64)', VALUE_OPTIONAL),
                'innFileName' => new external_value(PARAM_TEXT, 'INN File name', VALUE_OPTIONAL),
                'snilsFile' => new external_value(PARAM_RAW, 'SNILS File (base64)', VALUE_OPTIONAL),
                'snilsFileName' => new external_value(PARAM_TEXT, 'SNILS File name', VALUE_OPTIONAL),
                'sex' => new external_value(PARAM_TEXT, 'Sex', VALUE_OPTIONAL),
                'birthday' => new external_value(PARAM_TEXT, 'Birthday', VALUE_OPTIONAL),
                'serial' => new external_value(PARAM_TEXT, 'Passport Serial', VALUE_OPTIONAL),
                'number' => new external_value(PARAM_TEXT, 'Passport Number', VALUE_OPTIONAL),
                'whenIssued' => new external_value(PARAM_TEXT, 'Passport When Issued', VALUE_OPTIONAL),
                'whoIssued' => new external_value(PARAM_TEXT, 'Passport Who Issued', VALUE_OPTIONAL),
                'serialEdu' => new external_value(PARAM_TEXT, 'Education Serial', VALUE_OPTIONAL),
                'numberEdu' => new external_value(PARAM_TEXT, 'Education Number', VALUE_OPTIONAL),
                'whenIssuedEdu' => new external_value(PARAM_TEXT, 'Education When Issued', VALUE_OPTIONAL),
                'whoIssuedEdu' => new external_value(PARAM_TEXT, 'Education Who Issued', VALUE_OPTIONAL),
                'inGroup' => new external_value(PARAM_TEXT, 'Group ID', VALUE_OPTIONAL),
                'unemployed' => new external_value(PARAM_BOOL, 'Unemployed', VALUE_DEFAULT, false),
                'returnToJob' => new external_value(PARAM_BOOL, 'Return to Job', VALUE_DEFAULT, false),
                'imprisonment' => new external_value(PARAM_BOOL, 'Imprisonment', VALUE_DEFAULT, false),
                'insurance' => new external_value(PARAM_BOOL, 'Insurance', VALUE_DEFAULT, false),
                'parentalLeave' => new external_value(PARAM_BOOL, 'Parental Leave', VALUE_DEFAULT, false),
                'personalData' => new external_value(PARAM_BOOL, 'Personal Data Consent', VALUE_DEFAULT, false),
                'informationAboutPayer' => new external_value(PARAM_TEXT, 'Information About Payer', VALUE_OPTIONAL),
                'education' => new external_value(PARAM_TEXT, 'Education', VALUE_OPTIONAL),
                'educationLevel' => new external_value(PARAM_TEXT, 'Education Level', VALUE_OPTIONAL),
                'educationType' => new external_value(PARAM_TEXT, 'Education Type', VALUE_OPTIONAL),
                'education_level' => new external_value(PARAM_TEXT, 'Education level', VALUE_OPTIONAL),
                'nameMatchesPassport' => new external_value(PARAM_BOOL, 'Name matches passport', VALUE_DEFAULT, false),
                'individual' => new external_single_structure([], '1', VALUE_OPTIONAL),
                'individual_fullName' => new external_value(PARAM_TEXT, 'Full name of individual', VALUE_OPTIONAL),
                'individual_sex' => new external_value(PARAM_TEXT, 'Sex of individual', VALUE_OPTIONAL),
                'individual_citizenship' => new external_value(PARAM_TEXT, 'Citizenship of individual', VALUE_OPTIONAL),
                'individual_birthday' => new external_value(PARAM_TEXT, 'Birthday of individual', VALUE_OPTIONAL),
                'individual_document_type' => new external_value(PARAM_TEXT, 'Document type of individual', VALUE_OPTIONAL),
                'individual_passportPhotoScan' => new external_value(PARAM_RAW, 'Passport photo scan of individual', VALUE_OPTIONAL),
                'individual_passportPhotoScanName' => new external_value(PARAM_TEXT, 'Passport photo scan name of individual', VALUE_OPTIONAL),
                'individual_serial' => new external_value(PARAM_TEXT, 'Passport serial of individual', VALUE_OPTIONAL),
                'individual_number' => new external_value(PARAM_TEXT, 'Passport number of individual', VALUE_OPTIONAL),
                'individual_whoIssued' => new external_value(PARAM_TEXT, 'Passport issuer of individual', VALUE_OPTIONAL),
                'individual_whenIssued' => new external_value(PARAM_TEXT, 'Passport issue date of individual', VALUE_OPTIONAL),
                'individual_addressOfRegistration' => new external_value(PARAM_TEXT, 'Registration address of individual', VALUE_OPTIONAL),
                'individual_addressOfRegistrationData' => external_helper::dadata_suggestion_structure(),
                'individual_addressOfActualResidence' => new external_value(PARAM_TEXT, 'Actual residence address of individual', VALUE_OPTIONAL),
                'individual_addressOfActualResidenceData' => external_helper::dadata_suggestion_structure(),
                'individual_telephone' => new external_value(PARAM_TEXT, 'Telephone of individual', VALUE_OPTIONAL),
                'individual_email' => new external_value(PARAM_TEXT, 'Email of individual', VALUE_OPTIONAL),
                'individual_divisionCode' => new external_value(PARAM_TEXT, 'Email of individual', VALUE_OPTIONAL),
                'individual_passportRegistrationScan' => new external_value(PARAM_RAW, 'Passport registration scan of individual', VALUE_OPTIONAL),
                'individual_passportRegistrationScanName' => new external_value(PARAM_TEXT, 'Passport registration scan name of individual', VALUE_OPTIONAL),
                'individual_inn' => new external_value(PARAM_TEXT, 'INN of individual', VALUE_OPTIONAL),
                'individual_innScan' => new external_value(PARAM_RAW, 'INN scan of individual', VALUE_OPTIONAL),
                'individual_innScanName' => new external_value(PARAM_TEXT, 'INN scan name of individual', VALUE_OPTIONAL),
                'addressOfRegistration' => new external_value(PARAM_TEXT, 'Address of Registration', VALUE_OPTIONAL),
                'addressOfRegistrationData' => external_helper::dadata_suggestion_structure(),
                'addressOfActualResidenceData' => external_helper::dadata_suggestion_structure(),
                'addressOfActualResidence' => new external_value(PARAM_TEXT, 'Address of Actual Residence', VALUE_OPTIONAL),
                'scanPassportAddress' => new external_value(PARAM_TEXT, 'Scan Passport Address (base64)', VALUE_OPTIONAL),
                'scanPassportAddressName' => new external_value(PARAM_TEXT, 'Scan Passport Address file name', VALUE_OPTIONAL),
                'passportFile' => new external_value(PARAM_RAW, 'Passport File (base64)', VALUE_OPTIONAL),
                'passportFileName' => new external_value(PARAM_TEXT, 'Passport File name', VALUE_OPTIONAL),
                'eduFile' => new external_value(PARAM_RAW, 'Education File (base64)', VALUE_OPTIONAL),
                'eduFileName' => new external_value(PARAM_TEXT, 'Education File name', VALUE_OPTIONAL),
                'course_schedule' => new external_value(PARAM_TEXT, 'Course Schedule', VALUE_OPTIONAL),
                'document_type' => new external_value(PARAM_TEXT, 'Document Type', VALUE_OPTIONAL),
                'limitedHealth' => new external_value(PARAM_BOOL, 'Limited Health', VALUE_DEFAULT, false),
                'disabled' => new external_value(PARAM_BOOL, 'Disabled', VALUE_DEFAULT, false),
                'intellectualDisabilities' => new external_value(PARAM_BOOL, 'Intellectual Disabilities', VALUE_DEFAULT, false),
                'fullnameLE' => new external_value(PARAM_TEXT, 'Full Name LE', VALUE_OPTIONAL),
                'shortnameLE' => new external_value(PARAM_TEXT, 'Short Name LE', VALUE_OPTIONAL),
                'legalAddress' => new external_value(PARAM_TEXT, 'Legal Address', VALUE_OPTIONAL),
                'legalAddressData' => external_helper::dadata_suggestion_structure(),
                'postalAddress' => new external_value(PARAM_TEXT, 'Postal Address', VALUE_OPTIONAL),
                'postalAddressData' => external_helper::dadata_suggestion_structure(),
                'telephoneLE' => new external_value(PARAM_TEXT, 'Telephone LE', VALUE_OPTIONAL),
                'innLE' => new external_value(PARAM_TEXT, 'INN LE', VALUE_OPTIONAL),
                'kpp' => new external_value(PARAM_TEXT, 'KPP', VALUE_OPTIONAL),
                'bankDetails' => new external_value(PARAM_TEXT, 'Bank Details', VALUE_OPTIONAL),
                'accountNumber' => new external_value(PARAM_TEXT, 'Account Number', VALUE_OPTIONAL),
                'bik' => new external_value(PARAM_TEXT, 'BIK', VALUE_OPTIONAL),
                'divisionCode' => new external_value(PARAM_TEXT, 'Division Code', VALUE_OPTIONAL),
                'nameMismatchFile' => new external_value(PARAM_TEXT, 'nameMismatchFile', VALUE_OPTIONAL),
                'nameMismatchFileName' => new external_value(PARAM_TEXT, 'nameMismatchFileName', VALUE_OPTIONAL),
            ]
        );
    }

    public static function dadata_suggestion_structure(): external_single_structure
    {
        return new external_single_structure([
            'data' => new external_single_structure([
                'postal_code' => new external_value(PARAM_TEXT, 'Почтовый индекс', VALUE_OPTIONAL),
                'country' => new external_value(PARAM_TEXT, 'Страна', VALUE_OPTIONAL),
                'country_iso_code' => new external_value(PARAM_TEXT, 'ISO код страны', VALUE_OPTIONAL),
                'federal_district' => new external_value(PARAM_TEXT, 'Федеральный округ', VALUE_OPTIONAL),
                'region_fias_id' => new external_value(PARAM_TEXT, 'ФИАС ID региона', VALUE_OPTIONAL),
                'region_kladr_id' => new external_value(PARAM_TEXT, 'КЛАДР ID региона', VALUE_OPTIONAL),
                'region_iso_code' => new external_value(PARAM_TEXT, 'ISO код региона', VALUE_OPTIONAL),
                'region_with_type' => new external_value(PARAM_TEXT, 'Регион с типом', VALUE_OPTIONAL),
                'region_type' => new external_value(PARAM_TEXT, 'Тип региона', VALUE_OPTIONAL),
                'region_type_full' => new external_value(PARAM_TEXT, 'Полный тип региона', VALUE_OPTIONAL),
                'region' => new external_value(PARAM_TEXT, 'Регион', VALUE_OPTIONAL),
                'area_fias_id' => new external_value(PARAM_TEXT, 'ФИАС ID района', VALUE_OPTIONAL),
                'area_kladr_id' => new external_value(PARAM_TEXT, 'КЛАДР ID района', VALUE_OPTIONAL),
                'area_with_type' => new external_value(PARAM_TEXT, 'Район с типом', VALUE_OPTIONAL),
                'area_type' => new external_value(PARAM_TEXT, 'Тип района', VALUE_OPTIONAL),
                'area_type_full' => new external_value(PARAM_TEXT, 'Полный тип района', VALUE_OPTIONAL),
                'area' => new external_value(PARAM_TEXT, 'Район', VALUE_OPTIONAL),
                'city_fias_id' => new external_value(PARAM_TEXT, 'ФИАС ID города', VALUE_OPTIONAL),
                'city_kladr_id' => new external_value(PARAM_TEXT, 'КЛАДР ID города', VALUE_OPTIONAL),
                'city_with_type' => new external_value(PARAM_TEXT, 'Город с типом', VALUE_OPTIONAL),
                'city_type' => new external_value(PARAM_TEXT, 'Тип города', VALUE_OPTIONAL),
                'city_type_full' => new external_value(PARAM_TEXT, 'Полный тип города', VALUE_OPTIONAL),
                'city' => new external_value(PARAM_TEXT, 'Город', VALUE_OPTIONAL),
                'city_area' => new external_value(PARAM_TEXT, 'Район города', VALUE_OPTIONAL),
                'city_district_fias_id' => new external_value(PARAM_TEXT, 'ФИАС ID района города', VALUE_OPTIONAL),
                'city_district_kladr_id' => new external_value(PARAM_TEXT, 'КЛАДР ID района города', VALUE_OPTIONAL),
                'city_district_with_type' => new external_value(PARAM_TEXT, 'Район города с типом', VALUE_OPTIONAL),
                'city_district_type' => new external_value(PARAM_TEXT, 'Тип района города', VALUE_OPTIONAL),
                'city_district_type_full' => new external_value(PARAM_TEXT, 'Полный тип района города', VALUE_OPTIONAL),
                'city_district' => new external_value(PARAM_TEXT, 'Район города', VALUE_OPTIONAL),
                'settlement_fias_id' => new external_value(PARAM_TEXT, 'ФИАС ID населенного пункта', VALUE_OPTIONAL),
                'settlement_kladr_id' => new external_value(PARAM_TEXT, 'КЛАДР ID населенного пункта', VALUE_OPTIONAL),
                'settlement_with_type' => new external_value(PARAM_TEXT, 'Населенный пункт с типом', VALUE_OPTIONAL),
                'settlement_type' => new external_value(PARAM_TEXT, 'Тип населенного пункта', VALUE_OPTIONAL),
                'settlement_type_full' => new external_value(PARAM_TEXT, 'Полный тип населенного пункта', VALUE_OPTIONAL),
                'settlement' => new external_value(PARAM_TEXT, 'Населенный пункт', VALUE_OPTIONAL),
                'street_fias_id' => new external_value(PARAM_TEXT, 'ФИАС ID улицы', VALUE_OPTIONAL),
                'street_kladr_id' => new external_value(PARAM_TEXT, 'КЛАДР ID улицы', VALUE_OPTIONAL),
                'street_with_type' => new external_value(PARAM_TEXT, 'Улица с типом', VALUE_OPTIONAL),
                'street_type' => new external_value(PARAM_TEXT, 'Тип улицы', VALUE_OPTIONAL),
                'street_type_full' => new external_value(PARAM_TEXT, 'Полный тип улицы', VALUE_OPTIONAL),
                'street' => new external_value(PARAM_TEXT, 'Улица', VALUE_OPTIONAL),
                'house_fias_id' => new external_value(PARAM_TEXT, 'ФИАС ID дома', VALUE_OPTIONAL),
                'house_kladr_id' => new external_value(PARAM_TEXT, 'КЛАДР ID дома', VALUE_OPTIONAL),
                'house_cadnum' => new external_value(PARAM_TEXT, 'Кадастровый номер дома', VALUE_OPTIONAL),
                'house_flat_count' => new external_value(PARAM_INT, 'Количество квартир в доме', VALUE_OPTIONAL),
                'house_type' => new external_value(PARAM_TEXT, 'Тип дома', VALUE_OPTIONAL),
                'house_type_full' => new external_value(PARAM_TEXT, 'Полный тип дома', VALUE_OPTIONAL),
                'house' => new external_value(PARAM_TEXT, 'Дом', VALUE_OPTIONAL),
                'stead_fias_id' => new external_value(PARAM_TEXT, 'ФИАС ID земельного участка', VALUE_OPTIONAL),
                'stead_cadnum' => new external_value(PARAM_TEXT, 'Кадастровый номер земельного участка', VALUE_OPTIONAL),
                'stead_type' => new external_value(PARAM_TEXT, 'Тип земельного участка', VALUE_OPTIONAL),
                'stead_type_full' => new external_value(PARAM_TEXT, 'Полный тип земельного участка', VALUE_OPTIONAL),
                'stead' => new external_value(PARAM_TEXT, 'Земельный участок', VALUE_OPTIONAL),
                'block_type' => new external_value(PARAM_TEXT, 'Тип корпуса', VALUE_OPTIONAL),
                'block_type_full' => new external_value(PARAM_TEXT, 'Полный тип корпуса', VALUE_OPTIONAL),
                'block' => new external_value(PARAM_TEXT, 'Корпус', VALUE_OPTIONAL),
                'entrance' => new external_value(PARAM_TEXT, 'Подъезд', VALUE_OPTIONAL),
                'floor' => new external_value(PARAM_TEXT, 'Этаж', VALUE_OPTIONAL),
                'flat_fias_id' => new external_value(PARAM_TEXT, 'ФИАС ID квартиры', VALUE_OPTIONAL),
                'flat_cadnum' => new external_value(PARAM_TEXT, 'Кадастровый номер квартиры', VALUE_OPTIONAL),
                'flat_type' => new external_value(PARAM_TEXT, 'Тип квартиры', VALUE_OPTIONAL),
                'flat_type_full' => new external_value(PARAM_TEXT, 'Полный тип квартиры', VALUE_OPTIONAL),
                'flat' => new external_value(PARAM_TEXT, 'Квартира', VALUE_OPTIONAL),
                'room_fias_id' => new external_value(PARAM_TEXT, 'ФИАС ID помещения', VALUE_OPTIONAL),
                'room_cadnum' => new external_value(PARAM_TEXT, 'Кадастровый номер помещения', VALUE_OPTIONAL),
                'room_type' => new external_value(PARAM_TEXT, 'Тип помещения', VALUE_OPTIONAL),
                'room_type_full' => new external_value(PARAM_TEXT, 'Полный тип помещения', VALUE_OPTIONAL),
                'room' => new external_value(PARAM_TEXT, 'Помещение', VALUE_OPTIONAL),
                'flat_area' => new external_value(PARAM_FLOAT, 'Площадь квартиры', VALUE_OPTIONAL),
                'square_meter_price' => new external_value(PARAM_FLOAT, 'Цена за квадратный метр', VALUE_OPTIONAL),
                'flat_price' => new external_value(PARAM_FLOAT, 'Цена квартиры', VALUE_OPTIONAL),
                'postal_box' => new external_value(PARAM_TEXT, 'Абонентский ящик', VALUE_OPTIONAL),
                'fias_id' => new external_value(PARAM_TEXT, 'ФИАС ID', VALUE_OPTIONAL),
                'fias_code' => new external_value(PARAM_TEXT, 'Код ФИАС', VALUE_OPTIONAL),
                'fias_level' => new external_value(PARAM_INT, 'Уровень ФИАС', VALUE_OPTIONAL),
                'fias_actuality_state' => new external_value(PARAM_INT, 'Актуальность ФИАС', VALUE_OPTIONAL),
                'kladr_id' => new external_value(PARAM_TEXT, 'КЛАДР ID', VALUE_OPTIONAL),
                'geoname_id' => new external_value(PARAM_TEXT, 'Geoname ID', VALUE_OPTIONAL),
                'capital_marker' => new external_value(PARAM_INT, 'Признак столицы', VALUE_OPTIONAL),
                'okato' => new external_value(PARAM_TEXT, 'ОКАТО', VALUE_OPTIONAL),
                'oktmo' => new external_value(PARAM_TEXT, 'ОКТМО', VALUE_OPTIONAL),
                'tax_office' => new external_value(PARAM_TEXT, 'Налоговая инспекция', VALUE_OPTIONAL),
                'tax_office_legal' => new external_value(PARAM_TEXT, 'Юридическая налоговая инспекция', VALUE_OPTIONAL),
                'timezone' => new external_value(PARAM_TEXT, 'Часовой пояс', VALUE_OPTIONAL),
                'geo_lat' => new external_value(PARAM_FLOAT, 'Географическая широта', VALUE_OPTIONAL),
                'geo_lon' => new external_value(PARAM_FLOAT, 'Географическая долгота', VALUE_OPTIONAL),
                'beltway_hit' => new external_value(PARAM_TEXT, 'Признак нахождения в пределах МКАД', VALUE_OPTIONAL),
                'beltway_distance' => new external_value(PARAM_FLOAT, 'Расстояние от МКАД', VALUE_OPTIONAL),
                'metro' => new external_value(PARAM_TEXT, 'Метро', VALUE_OPTIONAL),
                'divisions' => new external_value(PARAM_TEXT, 'Подразделения', VALUE_OPTIONAL),
                'qc_geo' => new external_value(PARAM_INT, 'Код качества геокодирования', VALUE_OPTIONAL),
                'qc_complete' => new external_value(PARAM_INT, 'Код полноты', VALUE_OPTIONAL),
                'qc_house' => new external_value(PARAM_INT, 'Код качества дома', VALUE_OPTIONAL),
                'history_values' => new external_value(PARAM_TEXT, 'Исторические значения', VALUE_OPTIONAL),
                'unparsed_parts' => new external_value(PARAM_TEXT, 'Неразобранные части', VALUE_OPTIONAL),
                'source' => new external_value(PARAM_TEXT, 'Источник', VALUE_OPTIONAL),
                'qc' => new external_value(PARAM_INT, 'Код качества', VALUE_OPTIONAL),
            ], 'Данные адреса', VALUE_OPTIONAL),
            'unrestricted_value' => new external_value(PARAM_TEXT, 'Полный адрес', VALUE_OPTIONAL),
            'value' => new external_value(PARAM_TEXT, 'Адрес', VALUE_OPTIONAL),
        ], 'Структура ответа DaData', VALUE_OPTIONAL);
    }
}